version: "3.3"
services:
  flask-app:
    container_name: frontend
    image: dvsr1411/flaskapp:v1
    build:
      context: .
    restart: always
    depends_on:
      - mysqldb
    ports:
      - 5000:5000
    environment:
      MYSQL_HOST: mysqldb 
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_PASSWORD: Sathwik123
    networks:
      app-network:
        aliases:
          - mysqldb

  mysqldb:
    container_name: backend
    image: public.ecr.aws/docker/library/mysql:8.0.40
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: Sathwik123
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge
